# Generated by Django 4.1.2 on 2022-10-18 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bee_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hive',
            old_name='updated',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='observation',
            old_name='updated',
            new_name='modified',
        ),
    ]
