# Generated by Django 4.1.2 on 2022-10-18 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bee_backend', '0002_rename_updated_hive_modified_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hive',
            unique_together={('userid', 'number')},
        ),
    ]
