# Generated by Django 4.1.2 on 2022-10-18 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bee_backend', '0003_alter_hive_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='hive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='bee_backend.hive'),
        ),
    ]
