# Generated by Django 4.1.2 on 2022-10-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bee_backend', '0005_globalnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalnote',
            name='userid',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
