# Generated by Django 4.1.2 on 2022-10-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bee_backend', '0006_globalnote_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='varroa',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hive',
            name='number',
            field=models.CharField(max_length=16),
        ),
    ]
