# Generated by Django 4.1.2 on 2022-10-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bee_backend', '0007_observation_varroa_alter_hive_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='hive',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
