# Generated by Django 4.1.2 on 2022-10-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bee_backend', '0008_hive_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='hive',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
