# Generated by Django 4.1.2 on 2022-10-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bee_backend', '0009_hive_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalnote',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='observation',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
